### PR TITLE
Fixes #10 - Mac OS support is confirmed

### LINKED ISSUE #10: Confirm MacOS support
Since, the build works well on Linux doesn't mean it would work fine on MacOS too. It would be better if someone confirms on this.

### PR DESCRIPTION
**Pull request by heyAyushh**
Every file is building and working again.

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
I see that you skipped the GUI installation. Can you confirm it too?
And can you modify the `README.md` to specify what to do when you build for Mac OS?
Push the changes to your repo on `fix-mac-string-h` branch. I will pull from there and merge it into master. Put the commit link in your comment so that I can review your changes.

**Comment by heyAyushh** [comment]
I installed the GUI too and I confirm that it is working as expected.

screen shot 2017-10-25 at 17 16 53

**Comment by Compro-Prasad** [comment]
When will you be editing the `README.md` ?

**Comment by heyAyushh** [comment]
at 10:00 PM, Sorry my net got down..

**Comment by heyAyushh** [comment]
@Compro-Prasad 2da802253cff0dae48b486c58e5f964c1ccb5fa4

**Comment by heyAyushh** [comment]
@Compro-Prasad 7e5a4df0d71dae1eb9712f0a968c3c418bfc7722

**Comment by Compro-Prasad** [comment]
Why didn't you create a new pull request?

**Comment by heyAyushh** [comment]
Added some lines for macOS readme.md

**Pull request merged**
